[package]
name = "bpf-linker"
version = "0.9.0"
authors = ["Alessandro Decina <alessandro.d@gmail.com>"]
edition = "2018"

[dependencies]
# cli deps
structopt = { version = "0.3", optional = true }
clap = { version = "2", optional = true }
anyhow = { version = "1.0", optional = true }
simplelog = {version = "0.7.6", optional = true}

# lib deps
thiserror = { version = "1.0", optional = true }
ar = { version = "0.8", optional = true }
log = { version = "0.4", optional = true }
llvm-sys = { version = "110", optional = true }
rustc-llvm-proxy = { version = "0.2", optional = true, git = "https://github.com/alessandrod/rustc-llvm-proxy.git" }

[dev-dependencies]
compiletest_rs = { version = "*", git = "https://github.com/alessandrod/compiletest-rs" }

[[bin]]
name = "bpf-linker"

[features]
llvm = ["llvm-sys"]
llvm-proxy = [
    "rustc-llvm-proxy",
    "llvm-sys/no-llvm-linking",
    "llvm-sys/disable-alltargets-init"
]
lib = ["thiserror", "ar", "log"]
cli = ["structopt", "clap", "anyhow", "simplelog"]
default = ["cli", "lib", "llvm-proxy"]